// next/components/FourBoxes.tsx
import Image from "next/image";

interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  category: string;
}

interface FourBoxesProps {
  title: string;
  boxes: Project[];
  className?: string;
}

export default function FourBoxes({
  title,
  boxes,
  className = "",
}: FourBoxesProps) {
  return (
    <section
      className={`max-w-screen-xl mx-auto px-8 md:px-20 py-20 ${className}`}
    >
      <h2 className="text-3xl md:text-4xl font-bold text-center text-gray-800 mb-16 font-vollkorn">
        {title}
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        {boxes.map((box) => (
          <div
            key={box.id}
            className="bg-white rounded-lg shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300"
          >
            <div className="relative aspect-[4/3]">
              <Image
                src={box.image}
                alt={box.title}
                fill
                className="object-cover"
              />
            </div>
            <div className="p-6">
              <div className="text-sm text-leadmaster-red font-semibold mb-2">
                {box.category}
              </div>
              <h3 className="text-xl font-bold text-gray-800 mb-3 font-vollkorn">
                {box.title}
              </h3>
              <p className="text-gray-600 text-sm leading-relaxed">
                {box.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

// components/FourBoxes.vue
<template>
  <div class="four-boxes max-w-screen-xl mx-auto">
    <section class="mb-9 text-0 text-center">
      <h2 class="mb-3 text-3xl">{{ title }}</h2>
      <span class="inline-block h-px w-14 bg-yellow-600"></span>
    </section>
    <section class="px-2 grid grid-cols-2 lg:grid-cols-4">
      <div class="px-2 mx-auto mb-10 max-w-screen-sm md:max-w-max w-full"
        v-for="(box, index) in boxes" :key="'box' + index"
      >
        <a class="inline-block w-full" :href="box.link">
          <img
            :src="box.img"
            :alt="box.img_alt"
            class="w-full h-40 md:h-72 object-cover mb-4"
          />
          <h3 class="block text-lg">{{ box.title }}</h3>
        </a>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: "FourBoxes",
  props: ["title","boxes"],
  watch: {},
  data() {
    return {};
  },
  computed: {},
  methods: {},
  mounted() {},
  beforeMount() {},
};
</script>

<style lang="sass" scoped>
.four-boxes
  position: relative
</style>
