// next/components/ImgText.tsx
import Image from "next/image";

interface ImgTextProps {
  img: string;
  title: string;
  description: string;
  className?: string;
}

export default function ImgText({
  img,
  title,
  description,
  className = "",
}: ImgTextProps) {
  return (
    <section className={className}>
      <div className="flex flex-col lg:flex-row items-center gap-8 lg:gap-16">
        {/* Image */}
        <div className="w-full lg:w-1/2">
          <div className="relative aspect-[4/3] rounded-lg overflow-hidden shadow-lg">
            <Image src={img} alt={title} fill className="object-cover" />
          </div>
        </div>

        {/* Text Content */}
        <div className="w-full lg:w-1/2">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-6 font-vollkorn">
            {title}
          </h2>
          <div
            className="text-lg leading-relaxed text-gray-700"
            dangerouslySetInnerHTML={{ __html: description }}
          />
        </div>
      </div>
    </section>
  );
}

// components/ImgText.vue
<template>
  <section id="img-text" class="">
    <div class="flex flex-col sm:flex-row items-start lg:items-center">
      <div class="mb-10 sm:m-0 sm:w-1/3">
        <img
          :src="img"
          alt="Feature image"
          class="w-full h-full object-cover"
        />
      </div>
      <div class="flex-1 px-8 sm:px-16">
        <h3 class="text-2xl">
          {{ title }}
        </h3>
        <p class="text-lg">
          {{ description }}
        </p>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: "ImgText",
  props: ["img", "title", "description"],
  watch: {},
  data() {
    return {};
  },
  computed: {},
  methods: {},
  mounted() {},
  beforeMount() {},
};
</script>

<style lang="sass" scoped>
#img-text
  position: relative
</style>
