// next/components/RightJumbotron.tsx
import Image from "next/image";

interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  category: string;
}

interface RightJumbotronProps {
  content: Project;
  className?: string;
}

export default function RightJumbotron({
  content,
  className = "",
}: RightJumbotronProps) {
  return (
    <section className={`max-w-screen-xl mx-auto px-8 md:px-20 ${className}`}>
      <div className="flex flex-col lg:flex-row items-center gap-8 lg:gap-16">
        {/* Image */}
        <div className="w-full lg:w-1/2">
          <div className="relative aspect-[4/3] rounded-lg overflow-hidden shadow-lg">
            <Image
              src={content.image}
              alt={content.title}
              fill
              className="object-cover"
            />
          </div>
        </div>

        {/* Content */}
        <div className="w-full lg:w-1/2">
          <div className="text-leadmaster-red text-sm font-semibold mb-2">
            {content.category}
          </div>
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-6 font-vollkorn">
            {content.title}
          </h2>
          <p className="text-lg leading-relaxed text-gray-700">
            {content.description}
          </p>
        </div>
      </div>
    </section>
  );
}

// components/RightJumbotron.vue
<template>
  <section class="right-jumbotron">
    <div class="max-w-screen-xl mx-auto">
      <div class="flex flex-col md:flex-row items-start items-stretch">
        <div class="flex-1">
          <img class="w-full h-48 object-cover" :src="img" :alt="title">
        </div>
        <div class="md:w-1/5 relative md:order-first">
          <div class="text-container px-8 py-4">
            <h2 class="text-2xl md:text-4xl">
              {{ title }}
            </h2>
            <p class="text-xl md:text-2xl">
              {{ subtitle }}
            </p>
            <p class="text-base md:text-lg">
              {{ description }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: "RightJumbotron",
  props: ["content"],
  watch: {},
  data() {
    return {
      title: this.content.title,
      subtitle: this.content.subtitle,
      description: this.content.description,
      img: this.content.img
    };
  },
  computed: {},
  methods: {},
  mounted() {},
  beforeMount() {},
};
</script>

<style lang="sass" scoped>
.right-jumbotron
  position: relative
  img
    @include rwd-md
      height: 600px
  .text-container
    @include rwd-md
      width: 200%
      position: absolute
      left: 10%
      top: 40%
      transform: translate(0, -50%)
      background-color: rgba(229, 231, 235, 0.9)
</style>
