// components/Carousel.vue
<template>
  <section class="carousel">
    <v-carousel
      cycle
      height="100%"
      hide-delimiter-background
      hide-delimiters
    >
      <v-carousel-item
        v-for="(image, i) in images"
        :key="i"
        :src="image"
      >
      </v-carousel-item>
    </v-carousel>
    <div class="cover-text">
      <div class="
        h-full text-center
        max-w-screen-xl mx-auto
        p-10 sm:p-20 pt-24 sm:pt-36
        flex items-center justify-center
      ">
        <div class="tracking-wider font-bold">
          <h2 class="
            break-words sm:break-normal
            text-4xl sm:text-5xl
            mb-8
          ">
            {{ text.title }}
            <br>
            {{ text.title2 }}
          </h2>
          <p class="text-lg">
            {{ text.subtitle }}
          </p>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: "Carousel",
  props: ["images", "text"],
  data() {
    return {};
  },
  methods: {},
  mounted() {
  },
};
</script>

<style lang="sass" scoped>
.carousel::v-deep
  position: relative
  .v-window__prev
    display: none
    left: 0
    // @include rwd-sm
    //   display: block
  .v-window__next
    display: none
    right: 0
    // @include rwd-sm
    //   display: block
  &::after
    content: ''
    position: absolute
    top: 0
    left: 0
    width: 100%
    height: 100%
    z-index: 1
    background: linear-gradient(0deg, rgba(255, 219, 219, 1) 20%, rgba(255, 255, 255, .5))
  .cover-text
    position: absolute
    top: 0
    left: 0
    width: 100%
    height: 100%
    z-index: 2
    transition: all 1s
    h2, p
      opacity: 0
      animation-name: show-text
      animation-duration: 0.7s
      animation-fill-mode: forwards
    h2
      animation-delay: 2s
    p
      animation-delay: 3s

@keyframes show-text
  0%
    transform: translateX(100px)
    opacity: 0
  100%
    transform: translateX(0px)
    opacity: 1
</style>

// next/components/Carousel.tsx
"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { ChevronLeft, ChevronRight } from "lucide-react";

interface CarouselProps {
  images: any[];
  text: {
    title: string;
    title2: string;
    subtitle: string;
  };
  className?: string;
  style?: React.CSSProperties;
}

export default function Carousel({
  images,
  text,
  className = "",
  style,
}: CarouselProps) {
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 5000); // Change image every 5 seconds

    return () => clearInterval(timer);
  }, [images.length]);

  const goToPrevious = () => {
    setCurrentIndex(
      (prevIndex) => (prevIndex - 1 + images.length) % images.length
    );
  };

  const goToNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const goToSlide = (index: number) => {
    setCurrentIndex(index);
  };

  return (
    <div className={`relative overflow-hidden ${className}`} style={style}>
      {/* Image Container */}
      <div className="relative w-full h-full">
        {images.map((image, index) => (
          <div
            key={index}
            className={`absolute inset-0 transition-opacity duration-1000 ${
              index === currentIndex ? "opacity-100" : "opacity-0"
            }`}
          >
            <Image
              src={image}
              alt={`Carousel image ${index + 1}`}
              fill
              className="object-cover"
              priority={index === 0}
            />
            {/* Overlay */}
            <div className="absolute inset-0 bg-black bg-opacity-40"></div>
          </div>
        ))}
      </div>

      {/* Text Content */}
      <div className="absolute inset-0 flex items-center justify-center text-white z-10">
        <div className="text-center px-8">
          <h1 className="text-4xl md:text-6xl font-bold mb-4 font-vollkorn">
            {text.title}
          </h1>
          <h2 className="text-2xl md:text-4xl font-bold mb-6 font-vollkorn">
            {text.title2}
          </h2>
          <p className="text-lg md:text-xl max-w-2xl mx-auto">
            {text.subtitle}
          </p>
        </div>
      </div>

      {/* Navigation Arrows */}
      <button
        onClick={goToPrevious}
        className="absolute left-4 top-1/2 transform -translate-y-1/2 bg-black bg-opacity-50 hover:bg-opacity-70 text-white p-2 rounded-full transition-all duration-200 z-20"
        aria-label="Previous image"
      >
        <ChevronLeft size={24} />
      </button>

      <button
        onClick={goToNext}
        className="absolute right-4 top-1/2 transform -translate-y-1/2 bg-black bg-opacity-50 hover:bg-opacity-70 text-white p-2 rounded-full transition-all duration-200 z-20"
        aria-label="Next image"
      >
        <ChevronRight size={24} />
      </button>

      {/* Dots Indicator */}
      <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2 flex space-x-2 z-20">
        {images.map((_, index) => (
          <button
            key={index}
            onClick={() => goToSlide(index)}
            className={`w-3 h-3 rounded-full transition-all duration-200 ${
              index === currentIndex
                ? "bg-white"
                : "bg-white bg-opacity-50 hover:bg-opacity-75"
            }`}
            aria-label={`Go to slide ${index + 1}`}
          />
        ))}
      </div>
    </div>
  );
}
