// nuxt3/components/Nav.vue
<template>
  <header id="nav" class="text-white">
    <div class="max-w-screen-xl mx-auto">
      <div class="py-1 px-6 flex justify-between items-center" style="height: 80px">
        <NuxtLink to="/" class="inline-block px-4 py-1.5">
          <img src="@/assets/image/leadmaster_logo2.png" alt="Logo"
            class="p-px bg-white"
          />
        </NuxtLink>
        <nav class="hidden lg:block">
          <NuxtLink to="/about" class="inline-block p-2 md:px-8">About</NuxtLink>
          <NuxtLink to="/projects" class="inline-block p-2 md:px-8">Projects</NuxtLink>
          <NuxtLink to="/agent" class="inline-block p-2 md:px-8">Agent</NuxtLink>
          <NuxtLink to="/recruitment" class="inline-block p-2 md:px-8">Recruitment</NuxtLink>
        </nav>
        <div class="lg:hidden">
          <button @click.stop="drawer = !drawer"
            class="hamburger hamburger--collapse"
            type="button"
            :class="{ 'is-active': drawer }"
          >
            <span class="hamburger-box">
              <span class="hamburger-inner"></span>
            </span>
          </button>
        </div>
      </div>
    </div>
    <!-- 取代 v-navigation-drawer + v-overlay -->
    <aside class="navigation-drawer px-14 py-16" :class="{ open: drawer }">
      <NuxtLink to="/" class="block mx-auto w-24 mb-8">
        <img src="@/assets/image/leadmaster_logo.png" alt="Logo"
          class="inline-block bg-white rounded"
        />
      </NuxtLink>
      <nav class="mx-auto text-white text-2xl">
        <NuxtLink to="/" class="block mb-2 p-2">Home</NuxtLink>
        <NuxtLink to="/about" class="block mb-2 p-2">About</NuxtLink>
        <NuxtLink to="/projects" class="block mb-2 p-2">Projects</NuxtLink>
        <NuxtLink to="/agent" class="block mb-2 p-2">Agent</NuxtLink>
        <NuxtLink to="/recruitment" class="block mb-2 p-2">Recruitment</NuxtLink>
      </nav>
    </aside>
    <div v-if="drawer" class="drawer-overlay" @click="drawer = false"></div>
  </header>
</template>

<script setup>
const drawer = ref(false)
const route = useRoute()

watch(() => route.fullPath, () => {
  drawer.value = false
})
</script>

<style lang="sass" scoped>
#nav
  position: sticky
  top: 0
  left: 0
  z-index: 10
  box-shadow: 0px 0px 16px 2px rgb(79 64 53 / 20%)
  background-color: $leadmaster-red
  img
    width: 100px
    border: 1px solid white
    border-radius: 3px
    box-shadow: 0 0 0 3px #da1b0a inset
  .navigation-drawer
    position: fixed
    top: 0
    left: 0
    height: 100%
    width: 256px
    z-index: 30
    overflow-y: auto
    background-color: $leadmaster-red
    box-shadow: 0px 8px 10px -5px rgb(0 0 0 / 20%), 0px 16px 24px 2px rgb(0 0 0 / 14%)
    transform: translateX(-110%)
    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)
    &.open
      transform: translateX(0)
    @include rwd-lg
      display: none
  .drawer-overlay
    position: fixed
    top: 0
    left: 0
    width: 100%
    height: 100%
    z-index: 20
    background-color: rgba(33, 33, 33, 0.46)
    @include rwd-lg
      display: none
</style>

// next/components/Nav.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Menu, X } from "lucide-react";

export default function Nav() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
  };

  return (
    <header
      id="nav"
      className="text-white sticky top-0 left-0 z-10 shadow-lg bg-leadmaster-red"
    >
      <div className="max-w-screen-xl mx-auto">
        <div className="py-1 px-6 flex justify-between items-center h-20">
          <Link href="/" className="inline-block px-4 py-1.5">
            <Image
              src="/leadmaster_logo2.png"
              alt="Logo"
              width={100}
              height={40}
              className="p-px bg-white border border-white rounded shadow-[0_0_0_3px_#da1b0a_inset]"
            />
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden lg:block">
            <Link
              href="/about"
              className="inline-block p-2 md:px-8 hover:text-gray-200 transition-colors"
            >
              About
            </Link>
            <Link
              href="/projects"
              className="inline-block p-2 md:px-8 hover:text-gray-200 transition-colors"
            >
              Projects
            </Link>
            <Link
              href="/agent"
              className="inline-block p-2 md:px-8 hover:text-gray-200 transition-colors"
            >
              Agent
            </Link>
            <Link
              href="/recruitment"
              className="inline-block p-2 md:px-8 hover:text-gray-200 transition-colors"
            >
              Recruitment
            </Link>
          </nav>

          {/* Mobile Menu Button */}
          <div className="lg:hidden">
            <button
              onClick={toggleMenu}
              className="hamburger hamburger--collapse"
              type="button"
              aria-label="Toggle menu"
            >
              <span className="hamburger-box">
                <span className="hamburger-inner"></span>
              </span>
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Navigation Drawer */}
      {isMenuOpen && (
        <>
          <div
            className="fixed inset-0 bg-black bg-opacity-50 z-40"
            onClick={closeMenu}
          ></div>
          <div className="fixed top-0 right-0 h-full w-80 bg-leadmaster-red z-50 px-14 py-16">
            <div className="flex justify-between items-center mb-8">
              <Link href="/" className="block mx-auto w-24" onClick={closeMenu}>
                <Image
                  src="/leadmaster_logo.png"
                  alt="Logo"
                  width={96}
                  height={40}
                  className="inline-block bg-white rounded"
                />
              </Link>
              <button
                onClick={closeMenu}
                className="text-white hover:text-gray-200"
                aria-label="Close menu"
              >
                <X size={24} />
              </button>
            </div>

            <nav className="mx-auto text-white text-2xl">
              <Link
                href="/"
                className="block mb-2 p-2 hover:text-gray-200 transition-colors"
                onClick={closeMenu}
              >
                Home
              </Link>
              <Link
                href="/about"
                className="block mb-2 p-2 hover:text-gray-200 transition-colors"
                onClick={closeMenu}
              >
                About
              </Link>
              <Link
                href="/projects"
                className="block mb-2 p-2 hover:text-gray-200 transition-colors"
                onClick={closeMenu}
              >
                Projects
              </Link>
              <Link
                href="/agent"
                className="block mb-2 p-2 hover:text-gray-200 transition-colors"
                onClick={closeMenu}
              >
                Agent
              </Link>
              <Link
                href="/recruitment"
                className="block mb-2 p-2 hover:text-gray-200 transition-colors"
                onClick={closeMenu}
              >
                Recruitment
              </Link>
            </nav>
          </div>
        </>
      )}
    </header>
  );
}
