// nuxt3/components/Slogan.vue
<template>
  <section class="slogan relative bg-gray-100 mt-5 text-center">
    <h3 class="text-2xl md:text-4xl">{{ title }}</h3>
    <div class="max-w-screen-xl mx-auto pb-12 px-20">
      <div class="pt-10 flex flex-col md:flex-row justify-between">
        <div v-for="(slogan, index) in slogans" :key="'slogan' + index"
          class="flex-1 p-8"
        >
          <AppIcon :name="slogan.icon" :size="40" class="mb-5" />
          <p class="text-2xl">
            {{ slogan.text }}
          </p>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
defineProps(['title', 'slogans'])
</script>

<style lang="sass" scoped>
.slogan
  position: relative
  h3
    position: absolute
    top: 0
    left: 50%
    transform: translate(-50%, -50%)
</style>

// next/components/Slogan.tsx
import { Eye, Pencil, Wrench } from "lucide-react";

interface Slogan {
  icon: string;
  text: string;
}

interface SloganProps {
  title: string;
  slogans: Slogan[];
  className?: string;
}

const iconMap = {
  "mdi-eye": Eye,
  "mdi-lead-pencil": Pencil,
  "mdi-wrench": Wrench,
};

export default function Slogan({
  title,
  slogans,
  className = "",
}: SloganProps) {
  return (
    <section className={`bg-gray-50 py-20 ${className}`}>
      <div className="max-w-screen-xl mx-auto px-8 md:px-20">
        <h2 className="text-3xl md:text-4xl font-bold text-center text-gray-800 mb-16 font-vollkorn">
          {title}
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {slogans.map((slogan, index) => {
            const IconComponent =
              iconMap[slogan.icon as keyof typeof iconMap] || Eye;

            return (
              <div key={index} className="text-center">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-leadmaster-red text-white rounded-full mb-6">
                  <IconComponent size={32} />
                </div>
                <h3 className="text-xl font-semibold text-gray-800 font-vollkorn">
                  {slogan.text}
                </h3>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
